
version: '3.7'

 

services:

  redis:
    image: redis:6.0.6

    ports:
    - "6379"

    

  zookeeper:

    image: confluentinc/cp-zookeeper:5.5.2

    ports:

    - "2181:2181"

    environment:

      ZOOKEEPER_CLIENT_PORT: "2181"

 

  kafka:

    image: confluentinc/cp-kafka:5.5.1

    ports:

    - "19092:19092"

    environment:

      KAFKA_BROKER_ID: 0

      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"

      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:19092"

      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"

    depends_on:

    - "zookeeper"

  stedi:

    image: scmurdock/stedi
    
    ports:

    - "4567:4567"

    environment:

      REDIS_HOST: "redis"
      
      REDIS_PORT: "6379"

      REDIS_DB: "0"

<<<<<<< HEAD
      KAFKA_BROKER: "kafka:19092"
=======
      STEDI_REDIS_CONNECT: "redis:6379"

      KAFKA_HOST: "kafka"

      KAFKA_BROKER: "kafka:0"
>>>>>>> 3fc04c3f38b169ea1c13992750701b7311f57962

      KAFKA_RISK_TOPIC: "customer-risk-topic"
      
      STEDI_KAFKA_CONNECT: "kafka:19092"
    depends_on:

      - "redis"
      - "kafka"